### PR TITLE
Partial migration to .NET 5

### PR DESCRIPTION
**Pull request by SuperJMN**
Please, take a look to it. We need to push this project forward to keep up! It's an awesome physics engine.

### CODE REVIEW

**Comment by SuperJMN** [comment]
Includes Azure Pipelines to automate the create of NuGet packages. First pre-release version is already in Nuget.org

**Comment by Genbox** [comment]
Hi SuperJMN,

I spent almost every waking hour trying to keep up with tech changes, support requests, issues etc. that I simply burned out. Maintaining an open-source library for free only works when there is passion, and the passion left after maintaining it for 4 years. 

[Others](http://antirez.com/news/129) have felt the same.

I was about to start refurbishing another one of my projects, but the billion-dollar company behind the API decided that it was just too expensive to sponsor me $5/md to maintain it, so I've decided to look elsewhere. I can restart this project, but it would become a sponsored project (see [Fody](https://github.com/Fody/Fody)).

Thanks for your pull request, but most of all your enthusiasm.

**Comment by SuperJMN** [comment]
Ian, I'm appalled to read that. I have felt the same over the years with numerous projects I've worked, and it's something that worries me A LOT. That's precisely why I that our community as a whole needs to find a solution **to mitigate the side effects of most open source projects**, that are, in essentially, the effects of working for free.

The amount of work you put into this project is huge. Thanks for that. I wish I could fund the projects that really deserved it. This is one of them.

Some days ago, Mark Seemann (https://github.com/ploeh) posted this: https://blog.ploeh.dk/2021/03/22/the-dispassionate-posted this on his blog along with this tweet: https://twitter.com/ploeh/status/1373899742128828416?s=20. He's a developer I admire, and one of the most famous software craftsmen out there.

Also, I posted a poll regarding subsidization of open source: https://twitter.com/SuperJMN/status/1354371010481500161?s=20

In any case, if you want some help with the project, just tell me. I'm pretty new to physics engines, but I can do some "dev ops" tasks to keep this up and running. 

BTW: I'm 40, but when I was a child, I dreamed of making my own videogames. I created one when I was 15. I'm looking forward to creating it from scratch with current tech. 

As a side note, I'm experienced with advanced user interfaces like visual designers. I think I can create a "world" designer to make it easier to setup bodies and their relationships. Should you get enough energy to resume/restart this, I'll be here waiting for you input :)

Sincerely.
A passionate developer.

**Comment by Genbox** [comment]
I've updated the project to .NET Standard 2.0 - I'm not targeting .NET 5.0 just yet. Updated to the new MonoGame that targets .NET Standard as well. MG certainly have pulled together and created something awesome.

**Comment by Genbox** [comment]
I would have merged your pull request, but I need the files you deleted etc. as the project also works without MonoGame at all. The namespace in the files are the same (xna) to make migration between project types easy.

**Comment by SuperJMN** [comment]
Hey Ian! Thanks for making the required change!
I'll drop this PR :)

**Pull request closed without merging**
